image: ruby:3.1

pipelines:
  default:
    - step:
        name: Build Jekyll Site
        caches:
          - bundler
        script:
          - gem install bundler
          - bundle install
          - bundle exec jekyll build
        artifacts:
          - _site/**
    - step:
        name: Deploy to Bitbucket Pages
        deployment: production
        script:
          - pipe: atlassian/bitbucket-upload-file:0.5.0
            variables:
              FOLDER: "_site"
              TARGET: "docs"
